[build]
packages = [
    "pyroll"
]

[version]
path = "pyroll/sander_spreading.py"

[envs.default]
path = ".venv"
dependencies = [
    "pytest ~= 7.0",
    "pyroll-report ~= 2.0.0b",
]


[envs.docs]
path = ""
dependencies = [
    "matplotlib",
    "pygments ~= 2.0",
    "pytask ~= 0.2.0",
    "pytask_latex ~= 0.2.0",
    "jinja2",
    "toml"
]

[envs.docs.scripts]
build = "latexmk --cd --pdf --shell-escape docs/docs"

[envs.test]
path = ""

[envs.test.scripts]
all = "pytest"

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]